apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        volumeMounts:
          - mountPath: /root/.ollama
            name: ollama-storage
        ports:
        - containerPort: 11434
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "ollama run qwen2:0.5b"]
      volumes:
      - hostPath:
          path: /opt/ollama
          type: DirectoryOrCreate
        name: ollama-storage
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  labels:
    app: ollama
spec:
  type: NodePort
  selector:
    app: ollama
  ports:
  - protocol: TCP
    port: 11434
    targetPort: 11434
    nodePort: 31143

